name: lego
description: "Awesome Flutter Skeleon for starter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9
  path: ^1.8.0 #flutter drive 1.8.1 over error
  get: ^4.6.5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  cached_network_image: ^3.2.1
  connectivity_plus: ^5.0.2
  battery_plus: ^5.0.2
  device_info_plus: ^9.0.3
  network_info_plus: ^4.0.2
  sensors_plus: ^4.0.2
  share_plus: ^7.1.0
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.0
  intl: ^0.18.1
  flutter_native_splash: ^2.0.5
  tuple: ^2.0.0
  random_string: ^2.3.1
  english_words:
  device_preview: ^1.1.0
  http: ^1.1.0
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  platform: ^3.0.2
  sqflite: ^2.0.1
  flutter_phoenix: ^1.0.0
  faker_dart: ^0.2.1
  uuid: ^4.3.3
  flutter_oss_licenses: ^2.0.0+1
  flutter_mailer: ^2.0.1
  event_bus: ^2.0.0
  flutter_gen: ^5.1.0+1
  permission_handler: ^11.0.1
  google_mobile_ads: ^4.0.0

  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_performance: ^0.9.3+8
  firebase_crashlytics: ^3.4.9
  firebase_dynamic_links: ^5.4.8
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_web_auth: ^0.5.0
  kakao_flutter_sdk: ^1.8.0
  firebase_remote_config: ^4.3.8
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.14.0
  awesome_notifications: ^0.8.2
  cloud_functions: ^4.6.1
  contacts_service: ^0.6.3
  google_fonts: ^6.1.0
  clipboard: ^0.1.3
  flutter_screenutil: ^5.5.3+2
  after_layout: ^1.2.0
  infinite_listview: ^1.1.0
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_gradient_colors: ^2.1.1
  badges: ^3.0.2
  get_time_ago: ^1.1.3
  flutter_vibrate: ^1.3.0
  flex_color_scheme: ^7.3.1
  keyboard_attachable: ^2.1.0
  flutter_color: ^2.1.0
  modal_bottom_sheet: ^3.0.0-pre
  random_color: ^1.0.6-nullsafety
  styled_widget: ^0.4.0+3
  flutter_speed_dial: ^7.0.0
  sembast: ^3.1.1+1
  url_launcher: ^6.0.20
  geolocator: ^10.1.0
  distance: ^1.0.0
  latlong2: ^0.9.0
  location: ^5.0.3
  page_transition: ^2.0.9
  basic_utils: ^5.4.2
  auto_orientation: ^2.2.1
  need_resume: # ^1.0.6
    git: https://github.com/melodysdreamj/need_resume.git
  lottie: ^3.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  sembast_web: ^2.0.1+1
  flutter_svg: ^2.0.4
  flutter_fgbg: ^0.3.0
  flutter_easyloading: ^3.0.5
  timeago: ^3.2.2

  google_static_maps_controller: ^1.0.0
  flash: ^3.0.5+1
  back_button_interceptor: ^7.0.0
  telephony: ^0.2.0
  in_app_review: ^2.0.4
  firebase_app_check: ^0.2.1+5
  country_codes: ^2.1.1
  country_code_picker: ^3.0.0
  fluttertoast: ^8.2.4
  webview_flutter: ^4.0.0
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.9+1
  flutter_inappwebview: ^6.0.0-beta.22
  internet_connection_checker: ^1.0.0+1
  camera: ^0.10.3+2
  image_picker: ^1.0.7
  in_app_purchase: ^3.0.2
  video_player: ^2.4.0
  image: ^4.1.4
  screenshot: ^2.1.0
  images_picker: ^1.2.11
  unsplash_client: ^2.1.0+3

  flutter_html: ^3.0.0-alpha.6
  isolated_worker: ^0.1.1
  flutter_image_compress: ^2.0.4
  crop_your_image: ^0.7.2
  image_size_getter: ^2.1.2
  file_picker: ^6.1.1
  loader_overlay: ^4.0.0
  vibration: ^1.7.6
  material_color_gen: ^2.0.0
  flutter_riverpod: ^2.0.2
  adaptive_theme: ^3.1.1
  pointer_interceptor: ^0.10.0
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.1.1
  auto_app_translate:
  gap: ^3.0.1
  flutter_styled_toast: ^2.2.1
  flutter_contacts: ^1.1.7+1
  insta_assets_picker: ^2.2.1
  photo_manager: ^3.0.0-dev.5
  loading_indicator: ^3.1.1
  wechat_assets_picker:
  intl_phone_field: ^3.2.0
  flutter_zoom_drawer: ^3.1.1
  phone_numbers_parser: ^8.1.0

  # icons
  flutter_font_icons:
  material_design_icons_flutter:
  fluttericon:
  line_awesome_flutter: ^2.0.0
  eva_icons_flutter: ^3.1.0
  icofont_flutter:
  font_awesome_flutter:
  flutter_boxicons:

  junes_flutter_architecture: ^0.8.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  emulators: ^0.5.1

  freezed: ^2.0.3+1
  json_serializable: ^6.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.1.0+1
  inview_notifier_list: ^3.0.0
  test: ^1.17.12
  process_run: ^0.14.1+3
  auto_store_translate:
  auto_screenshot_translate:
  another_flushbar: ^1.12.30




flutter_gen:
  output: lib/util/params # Optional (default: lib/gen/)
  line_length: 1000

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/illu/
    - assets/launcher_icons/
    - assets/lottie/
    - assets/splash/
    - assets/svg.icon/
    - assets/svg.icon/instagram/
    - assets/localization.csv

flutter_icons:
  image_path_android: "assets/launcher_icons/android.png"
  image_path_ios: "assets/launcher_icons/ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher_icons/android.png" # only available for Android 8.0 devices and above

flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/splash/background.png"
  image: assets/splash/icon.png

  color_dark: "#ffffff"
  ##background_image_dark: "assets/dark-background.png"
  image_dark: assets/splash/icon.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  fullscreen: true

# ➜ flutter packages pub run build_runner build --delete-conflicting-outputs
targets:
  $default:
    builders:
      your_builder:
        generate_for:
          - lib/**/*.dart
      mockito:mockBuilder:
        enabled: false
      json_serializable:
        enabled: false
      freezed:
        enabled: false
      hive_generator:
        enabled: false
      flutter_launcher_icons:
        enabled: true
      flutter_native_splash:
        enabled: true
      flutter_gen:
        enabled: true
      isar_generator:
        enabled: true
